# Customer Churn Prediction

In [1]:
import pandas as pd
from password import password
from sqlalchemy import create_engine

In [2]:
df_1 = pd.read_csv("data/sampleSubmission.csv")
df_2 = pd.read_csv("data/test.csv")
df_3 = pd.read_csv("data/train.csv")
m1_df = df_2.merge(df_1)
main_df = m1_df.append(df_3)
main_df.drop(["id"], inplace = True, axis = 1)
main_df.head(15)

/var/folders/rz/vqbs_7nd1lb3tq1xmr33wlx80000gn/T/ipykernel_58316/218903713.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  main_df = m1_df.append(df_3)

,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn
0,KS,128,area_code_415,no,yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,yes
1,AL,118,area_code_510,yes,no,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,no
2,IA,62,area_code_415,no,no,0,120.7,70,20.52,307.2,76,26.11,203.0,99,9.14,13.1,6,3.54,4,no
3,VT,93,area_code_510,no,no,0,190.7,114,32.42,218.2,111,18.55,129.6,121,5.83,8.1,3,2.19,3,yes
4,NE,174,area_code_415,no,no,0,124.3,76,21.13,277.1,112,23.55,250.7,115,11.28,15.5,5,4.19,3,yes
5,IL,142,area_code_415,no,no,0,84.8,95,14.42,136.7,63,11.62,250.5,148,11.27,14.2,6,3.83,2,no
6,LA,172,area_code_408,no,no,0,212.0,121,36.04,31.2,115,2.65,293.3,78,13.20,12.6,10,3.40,3,no
7,GA,72,area_code_415,no,yes,37,220.0,80,37.40,217.3,102,18.47,152.8,71,6.88,14.7,6,3.97,3,no
8,NJ,149,area_code_408,no,no,0,140.4,94,23.87,271.8,92,23.10,188.3,108,8.47,11.1,9,3.00,1,no
9,ID,119,area_code_415,no,no,0,159.1,114,27.05,231.3,117,19.66,143.2,91,6.44,8.8,3,2.38,5,yes
10,WY,87,area_code_415,no,no,0,151.0,83,25.67,219.7,116,18.67,203.9,127,9.18,9.7,3,2.62,5,no
11,WI,68,area_code_415,no,no,0,148.8,70,25.30,246.5,164,20.95,129.8,103,5.84,12.1,3,3.27,3,no
12,MN,74,area_code_510,no,yes,33,193.7,91,32.93,246.1,96,20.92,138.0,92,6.21,14.6,3,3.94,2,no
13,CO,55,area_code_408,no,yes,25,165.6,123,28.15,136.1,95,11.57,175.7,90,7.91,11.0,2,2.97,3,no
14,TX,106,area_code_510,no,no,0,210.6,96,35.80,249.2,85,21.18,191.4,88,8.61,12.4,1,3.35,2,no

In [3]:
main_df.isnull().any()

state                            False
account_length                   False
area_code                        False
international_plan               False
voice_mail_plan                  False
number_vmail_messages            False
total_day_minutes                False
total_day_calls                  False
total_day_charge                 False
total_eve_minutes                False
total_eve_calls                  False
total_eve_charge                 False
total_night_minutes              False
total_night_calls                False
total_night_charge               False
total_intl_minutes               False
total_intl_calls                 False
total_intl_charge                False
number_customer_service_calls    False
churn                            False
dtype: bool

In [4]:
main_df.dtypes

state                             object
account_length                     int64
area_code                         object
international_plan                object
voice_mail_plan                   object
number_vmail_messages              int64
total_day_minutes                float64
total_day_calls                    int64
total_day_charge                 float64
total_eve_minutes                float64
total_eve_calls                    int64
total_eve_charge                 float64
total_night_minutes              float64
total_night_calls                  int64
total_night_charge               float64
total_intl_minutes               float64
total_intl_calls                   int64
total_intl_charge                float64
number_customer_service_calls      int64
churn                             object
dtype: object

In [5]:
main_df['churn'] = main_df['churn'].map({'yes':1 ,'no':0})
main_df.head(10)

,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn
0,KS,128,area_code_415,no,yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,1
1,AL,118,area_code_510,yes,no,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,0
2,IA,62,area_code_415,no,no,0,120.7,70,20.52,307.2,76,26.11,203.0,99,9.14,13.1,6,3.54,4,0
3,VT,93,area_code_510,no,no,0,190.7,114,32.42,218.2,111,18.55,129.6,121,5.83,8.1,3,2.19,3,1
4,NE,174,area_code_415,no,no,0,124.3,76,21.13,277.1,112,23.55,250.7,115,11.28,15.5,5,4.19,3,1
5,IL,142,area_code_415,no,no,0,84.8,95,14.42,136.7,63,11.62,250.5,148,11.27,14.2,6,3.83,2,0
6,LA,172,area_code_408,no,no,0,212.0,121,36.04,31.2,115,2.65,293.3,78,13.20,12.6,10,3.40,3,0
7,GA,72,area_code_415,no,yes,37,220.0,80,37.40,217.3,102,18.47,152.8,71,6.88,14.7,6,3.97,3,0
8,NJ,149,area_code_408,no,no,0,140.4,94,23.87,271.8,92,23.10,188.3,108,8.47,11.1,9,3.00,1,0
9,ID,119,area_code_415,no,no,0,159.1,114,27.05,231.3,117,19.66,143.2,91,6.44,8.8,3,2.38,5,1

In [6]:
main_df.drop(['state', 'area_code'], inplace=True, axis=1)
main_df.head(10)

,account_length,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn
0,128,no,yes,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,1
1,118,yes,no,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,0
2,62,no,no,0,120.7,70,20.52,307.2,76,26.11,203.0,99,9.14,13.1,6,3.54,4,0
3,93,no,no,0,190.7,114,32.42,218.2,111,18.55,129.6,121,5.83,8.1,3,2.19,3,1
4,174,no,no,0,124.3,76,21.13,277.1,112,23.55,250.7,115,11.28,15.5,5,4.19,3,1
5,142,no,no,0,84.8,95,14.42,136.7,63,11.62,250.5,148,11.27,14.2,6,3.83,2,0
6,172,no,no,0,212.0,121,36.04,31.2,115,2.65,293.3,78,13.20,12.6,10,3.40,3,0
7,72,no,yes,37,220.0,80,37.40,217.3,102,18.47,152.8,71,6.88,14.7,6,3.97,3,0
8,149,no,no,0,140.4,94,23.87,271.8,92,23.10,188.3,108,8.47,11.1,9,3.00,1,0
9,119,no,no,0,159.1,114,27.05,231.3,117,19.66,143.2,91,6.44,8.8,3,2.38,5,1

In [7]:
main_df.nunique()

account_length                    218
international_plan                  2
voice_mail_plan                     2
number_vmail_messages              48
total_day_minutes                1961
total_day_calls                   123
total_day_charge                 1961
total_eve_minutes                1879
total_eve_calls                   126
total_eve_charge                 1659
total_night_minutes              1853
total_night_calls                 131
total_night_charge               1028
total_intl_minutes                170
total_intl_calls                   21
total_intl_charge                 170
number_customer_service_calls      10
churn                               2
dtype: int64

In [8]:
# Convert categorical data to numeric with `pd.get_dummies`
list_m = main_df.dtypes[main_df.dtypes == "object"].index.tolist()

ml_df = pd.get_dummies(main_df, prefix=list_m, drop_first=True)
ml_df

,account_length,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn,international_plan_yes,voice_mail_plan_yes
0,128,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,1,0,1
1,118,0,223.4,98,37.98,220.6,101,18.75,203.9,118,9.18,6.3,6,1.70,0,0,1,0
2,62,0,120.7,70,20.52,307.2,76,26.11,203.0,99,9.14,13.1,6,3.54,4,0,0,0
3,93,0,190.7,114,32.42,218.2,111,18.55,129.6,121,5.83,8.1,3,2.19,3,1,0,0
4,174,0,124.3,76,21.13,277.1,112,23.55,250.7,115,11.28,15.5,5,4.19,3,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4245,83,0,188.3,70,32.01,243.8,88,20.72,213.7,79,9.62,10.3,6,2.78,0,0,0,0
4246,73,0,177.9,89,30.24,131.2,82,11.15,186.2,89,8.38,11.5,6,3.11,3,0,0,0
4247,75,0,170.7,101,29.02,193.1,126,16.41,129.1,104,5.81,6.9,7,1.86,1,0,0,0
4248,50,40,235.7,127,40.07,223.0,126,18.96,297.5,116,13.39,9.9,5,2.67,2,0,0,1
4249,86,34,129.4,102,22.00,267.1,104,22.70,154.8,100,6.97,9.3,16,2.51,0,0,0,1

In [9]:
ml_df.nunique()

account_length                    218
number_vmail_messages              48
total_day_minutes                1961
total_day_calls                   123
total_day_charge                 1961
total_eve_minutes                1879
total_eve_calls                   126
total_eve_charge                 1659
total_night_minutes              1853
total_night_calls                 131
total_night_charge               1028
total_intl_minutes                170
total_intl_calls                   21
total_intl_charge                 170
number_customer_service_calls      10
churn                               2
international_plan_yes              2
voice_mail_plan_yes                 2
dtype: int64

In [10]:
pd.set_option('display.max_rows', 100)
ml_df.isnull().any()

account_length                   False
number_vmail_messages            False
total_day_minutes                False
total_day_calls                  False
total_day_charge                 False
total_eve_minutes                False
total_eve_calls                  False
total_eve_charge                 False
total_night_minutes              False
total_night_calls                False
total_night_charge               False
total_intl_minutes               False
total_intl_calls                 False
total_intl_charge                False
number_customer_service_calls    False
churn                            False
international_plan_yes           False
voice_mail_plan_yes              False
dtype: bool

In [11]:
ml_df.dtypes

account_length                     int64
number_vmail_messages              int64
total_day_minutes                float64
total_day_calls                    int64
total_day_charge                 float64
total_eve_minutes                float64
total_eve_calls                    int64
total_eve_charge                 float64
total_night_minutes              float64
total_night_calls                  int64
total_night_charge               float64
total_intl_minutes               float64
total_intl_calls                   int64
total_intl_charge                float64
number_customer_service_calls      int64
churn                              int64
international_plan_yes             uint8
voice_mail_plan_yes                uint8
dtype: object

In [12]:
main_df.to_csv("data/Curated_Data.csv")

In [15]:
protocol = 'postgresql'
username = 'postgres'
password = password
host = 'localhost'
port = 5432
database_name = 'churn_pred'
rds_connection_string = f'{protocol}://{username}:{password}@{host}:{port}/{database_name}'
engine = create_engine(rds_connection_string)

In [16]:
engine.table_names()

/var/folders/rz/vqbs_7nd1lb3tq1xmr33wlx80000gn/T/ipykernel_58316/4162273999.py:1: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  engine.table_names()

['fact_churn']

In [17]:
ml_df.to_sql(name='fact_churn', con=engine, if_exists='append', index=False)

1000

In [66]:
from selenium import webdriver
import chromedriver_binary
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
import time
chrome_options = Options()
#chrome_options.add_argument("--disable-extensions")
#chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--headless")
#chrome_options.headless = True
#chrome_options.add_argument("--start-maximized")
webdriver = webdriver.Chrome(options=chrome_options)
webdriver.implicitly_wait(10)
url = 'https://2021.ai/offerings/asset-store/customer-churn-prediction/'
webdriver.get(url)
#accept_cookies_settings = webdriver.find_element(by=By.XPATH, value='//*[@id="coiPage-1"]/div[2]/div[1]/button[3]')
#accept_cookies_settings.click()
print("Please answer the following questions: ")
print("If no values are available, please keep blank or add a zero")
webdriver.implicitly_wait(10)
time.sleep(2)
customers = input("How many customers do you currently have? --> ")
cust_worth = input("What is the average individual customer worth? --> ")
cust_lost = input("How many customers you lost last year? --> ")
model_acc = input("What is your ML model accuracy? --> ")
ret_cus = input("What is the percentage of customers that you think you can retain? --> ")
inputElement = webdriver.find_element("id", "customers")
inputElement.clear()
inputElement.send_keys(customers)
inputElement = webdriver.find_element("id", "customerValue")
inputElement.clear()
inputElement.send_keys(cust_worth)
inputElement = webdriver.find_element("id", "customersLost")
inputElement.clear()
inputElement.send_keys(cust_lost)
expand = webdriver.find_element(by=By.XPATH, value='//*[@id="post-251035"]/div/div/div/div[4]/div[5]/div/div/h3')
expand.click()
inputElement = webdriver.find_element("id", "detectChurn")
inputElement.clear()
inputElement.send_keys(model_acc)
inputElement = webdriver.find_element("id", "retainCustomers")
inputElement.clear()
inputElement.send_keys(ret_cus)
print("-----------------------------------------------")
print("-----------------------------------------------")
print("Based on the provided values:")
cr = webdriver.find_element(By.ID, 'churnRate')
print(f'  1. The Churn rate is {cr.text}%')
rl = webdriver.find_element(By.ID, 'revenueLost')
if rl.text == "NaN":
    print("  2. No Revenue data available")
else: print(f'  2. The Revenue lost is {rl.text}')
if ((model_acc.strip() != "" and ret_cus.strip() != "") | (model_acc != 0 and ret_cus != 0)):
    rd = webdriver.find_element(By.ID, 'reduceChurn')
    print(f'  3. You can reduce the Churn rate by {rd.text}%')
    rc = webdriver.find_element(By.ID, 'recoveredCustomers')
    print(f'  4. You can retain {rc.text} customers at risk')
    rl = webdriver.find_element(By.ID, 'recoveredRevenue')
    if rl.text == "NaN":
        print ("  5. No recovered Revenue data available")
    else: print(f'  5. The recovered Revenue will be {rl.text}')
    print("Thank you!")
else: print("Thank you!")

Please answer the following questions:
If no values are available, please keep blank or add a zero
How many customers do you currently have? --> 50000
What is the average individual customer worth? --> 15
How many customers you lost last year? --> 3750
What is your ML model accuracy? --> 83.5
What is the percentage of customers that you think you can retain? --> 60
-----------------------------------------------
-----------------------------------------------
Based on the provided values:
  1. The Churn rate is 8%
  2. The Revenue lost is 56,250
  3. You can reduce the Churn rate by 4%
  4. You can retain 1,879 customers at risk
  5. The recovered Revenue will be 28,181
Thank you!